# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aOwGx75aMnv8HPk-NLSEKpqjkfcc_12W
"""

import numpy as np

numbers =np.array([45,78,56,456])
type(numbers)
numbers

np.array([[45,68,79], [78,659,782]])

np.array([2,4,6,8,10,12,14,16,18,20])

np.array([[2,4,6,8,10],[1,3,5,7,9]])

#array attribute
integers = np.array([[2,4,6,8,10],[1,3,5,7,9]])
float = np.array([0.1, 0.2, 0.3, 0.9, 0.7 ,0.5])

float

float.dtype

float.ndim

float.shape

float.size

float.itemsize

for i in integers.flat:
  print(i, end='')

#create array   wih specfiic value
np.zeros(15)

np.ones((6,9), dtype=int)

np.full((3,5),45)

import numpy as np
np.arange(6)

np.arange(5,10)

np.arange(5,10, 2)

np.linspace(1,7,num=10)

np.arange(1,21).reshape(4,5)

np.arange(1,100001).reshape(4,25000)

#array operator
numbers =np.arange(1,7)

numbers

numbers*2

numbers**3

numbers +=10

numbers

numbers2 = np.linspace(1,6, 6)

numbers2

numbers * numbers2

numbers >= 13

numbers <= numbers2

